###ユーザー情報取得

GET http://localhost:8000/api/users/1
Accept: application/json
Accept:application/json

###アイテム取得

GET http://localhost:8000/api/items/1
Accept: application/json

###ユーザー登録

POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "みうら",
    "password": "Fennekin"
}
