##ユーザー##

###ユーザー登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "ki"
}

###ユーザー情報取得
GET http://localhost:8000/api/users/2
Accept: application/json
Authorization: Bearer 2|0SJinYabp0J8OxLJUAaGodUuf15Vzp1UoADKyHN196a655f3

##ランキング##

###ランキング更新
POST http://localhost:8000/api/ranking/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|0SJinYabp0J8OxLJUAaGodUuf15Vzp1UoADKyHN196a655f3

{
    "stageID": 1,
    "userID": 1,
    "highScore": 100
}

###ランキング表示
GET http://localhost:8000/api/ranking/show/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|0SJinYabp0J8OxLJUAaGodUuf15Vzp1UoADKyHN196a655f3
